# Generated by Django 3.2.7 on 2021-09-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('player_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Player ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Has checked-in')),
                ('match_checked_in', models.BooleanField(default=False, verbose_name='Checked-in for match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('discord_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Discord ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('round', models.IntegerField(verbose_name='Round')),
                ('set', models.CharField(max_length=3, verbose_name='Set')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='tournament.team', verbose_name='Team 1')),
                ('team2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='tournament.team', verbose_name='Team 2')),
            ],
        ),
    ]
